[package]
name = "clausewitz-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
time = "0.3.5"
anyhow = "1.0.52"

[dev-dependencies]
memmap = "0.7.0"